### ISSUE TITLE
Prohlížečka PDF - označování a kopírování textu

### ISSUE THREAD

**Issue by krizovj** [incad/K5Journals#57]
bylo by možné aktualizovat prohlížečku PDF, aby šel označovat a kopírovat text a vyhledávat (Ctrl + F)? 
V Krameriovi to jde:
https://kramerius.lib.cas.cz/client/handle/uuid:47c7e0d4-1ea7-4a6c-b52c-9d358d336f11

**Comment by krizovj** [comment]
Funguje to. Díky. 
Šlo by, aby se v těch PDF zvýrazňovaly všechny výsledky vyhledávání a ne jen přesné shody?

**Comment by albertoh** [comment]
Implementoval jsem kompromis:
Kdyz hledame vyrazy "kdekoliv", pri nasledne zobrazeni clanku, zobrazi se nalezene i s variacemi.
Napriklad clanek "Estrogeny, paměť, bolest a ochrana neuronů" pri hledani "ochrana hormony"
http://147.231.63.181/k5journals/vesmir/hledat/cokoliv;criteria=%5B%7B%22operator%22:%22AND%22,%22value%22:%22ochrana%20hormony%22%7D%5D;date=%5B0,1%5D;start=0

**Comment by krizovj** [comment]
ok, díky

**Comment by albertoh** [comment]
Opraveno zobrazeni scrollbar v IE
