### ISSUE TITLE
Vyhledávání - rubriky a klíčová slova

### ISSUE THREAD

**Issue by krizovj** [incad/K5Journals#59]
Když chci vyhledávat v klíčových slovech z vyhledávacího pole a ne z rejstříku, tak to jde pouze když je to klíčové slovo úplně přesně a navíc jen když má kolem sebe uvozovky. Jinak to nic nenajde.

Příklad: 
Vyhledat klíčová slova: 18. století 0, "18. století" 2

Šlo by to udělat tak, že pokud si vyberu, že chci vyhledávat klíčová slova a něco začnu psát, tak že se rozbalí ten našeptávač jako je v rejstříku? 

U rubrik je to stejně, musím napsat tu rubriku úplně přesně a do uvozovek. Takže když chci hledat v rubrice zprávy, tak musím zadat "news" a to uživatel nemůže vědět, že má zadat právě tohle a ještě v uvozovkách. 
Mělo by to fungovat tak, že si vyberu vyhledávat v rubrikách a zadám třeba recenze nebo zprávy a najde mi to recenze nebo zprávy.

**Comment by krizovj** [comment]
Už je tam našeptávač, to je OK. Ale pořád tam musím napsat uvozovky, i když je to vybrané z toho našeptávače:

1. Začnu psát a vyleze našeptávač - vyberu z něj klíčové slovo
![klicslova](https://user-images.githubusercontent.com/21309201/42624918-ceb37ad6-85c6-11e8-9fb1-29b3833f6ab6.jpg)

2. Výsledky 
![naseptavacklicslova](https://user-images.githubusercontent.com/21309201/42624928-d3c24a02-85c6-11e8-946a-0807cf2ab31a.jpg)

3. Výsledky po přidání uvozovek
![klicslovauvozovky](https://user-images.githubusercontent.com/21309201/42624933-d7eb3af8-85c6-11e8-972f-b915df556c36.jpg)

Potřebovala bych, abych tam nemusela dávat ty uvozovky. Zobrazují se tam, i když se do výsledků proklikám z rejstříku klíčových slov.

**Comment by krizovj** [comment]
A teď jsem si všimla, že u některých klíčových slov mi to funguje :) 
Třeba u klíčového slova "baroko", nebo "bibliography", atd. Je jich docela hodně, kde to funguje. Nemůže to být třeba tím, že to funguje jen u normálních klíčových slov a že dělá problémy, když je to jméno, nebo když jsou v tom čísla apod?

**Comment by krizovj** [comment]
Teď mě napadlo, jestli by to nemohlo být tím, že jde o více než jedno slovo? Zatím to funguje jen u jednoslovných termínů, jak to má více slov, tak už to nejde.

**Comment by krizovj** [comment]
Zkoušela jsem to v Chromu, Mozille a Opeře. IE nefunguje, viz https://github.com/incad/K5Journals/issues/58

**Comment by krizovj** [comment]
Ještě bych měla jeden požadavek k rubrikám. Když jsem tam teď zkoušela nahrát ty další časopisy, tak jsem zjistila, že u toho článku nemusí být uveden údaj o tom, co je to za článek (rubriku). Bylo by možné, když tam nebude v elementu genre uveden type, tak se článek zařadí automaticky do rubriky "Články"? 
Takové články, které to tam nemají se totiž pak nezobrazí v prohlížečce (v Archivu jsou).

Prostě je to v metadatech jen takto:
<mods:genre>article</mods:genre>

**Comment by albertoh** [comment]
Jaky uuid ma ten clanek? (abych se podival na cele mods)

**Comment by krizovj** [comment]
Třeba tenhle: 
uuid:0fe412e6-0bde-4e32-a3af-fc265e5ed67d
Je jich docela hodně, asi jsme to tam dříve neuváděli, ono to ani podle standardu NDK není povinné.

**Comment by albertoh** [comment]
Takze, kdyz tam je ten tag 
`<mods:genre>article</mods:genre>` pridam ho
Tak?

**Comment by krizovj** [comment]
Ano, když bude v záznamu `<mods:genre>article</mods:genre>` tak vznikne nová rubrika s názvem Články, kam se budou řadit tyto články.

**Comment by krizovj** [comment]
Vyrobí se nová rubrika, ale ty články se mi nezobrazují v prohlížečce.

**Comment by krizovj** [comment]
Mohl byste to, prosím, dát zase zpátky jak to bylo? Tedy že se nebude automaticky vyrábět ta rubrika Články? Kdybychom to tak udělali, tak se nám rozhodí Knihy a dějiny. Takže prostě před nasazením každého nového časopisu projdeme ta metadata a "type" doplníme všude. 
Moc díky a omlouvám se

**Comment by albertoh** [comment]
Jaky ma problem Knihy a dějiny?
Ze ma oba?

**Comment by krizovj** [comment]
Ano, bohužel, třeba tady:
https://kramerius.lib.cas.cz/search/handle/uuid:c18efa1f-2981-4e3e-b11f-eccb6060db33 
A bude pro nás jednodušší to u všech nových časopisů opravit než se ten jejich web zveřejní než to teď rychle vše měnit u Knih a dějin. Navíc ještě tak do konce prázdnin nemůžeme nic dávat do našeho ostrého Krameria, takže to teď ani opravit nemůžeme.

**Comment by albertoh** [comment]
Pockejte, zkusim zpracovat tu situaci

**Comment by albertoh** [comment]
Zkuste ted.
Ja jsem reindexoval Number 1-2. 2014 ( uuid:a65c817c-2b59-42a8-9d63-60bec1301932 )
Ted je to videt jako "Clanky", proto ze v metadatech se vyskytuje driv nez "main article"

Staci tak?

**Comment by krizovj** [comment]
Bohužel ne, ptž to vždycky nejsou pouze "hlavní články", ale taky třeba "zprávy", "recenze" atd. Teď je to všechno v rubrice "Články". Takže jednodušší asi bude vrátit to zpátky. Vážně se moc omlouvám. My to prostě u všech příštích časopisů upravíme tak, abychom ten type měli všude no. Jinak to asi udělat nepůjde, máme prostě ta metadata trochu chaotická.

**Comment by albertoh** [comment]
Ok

**Comment by albertoh** [comment]
Vraceno, reindexovano.
http://147.231.63.181/k5journals/kad/article/uuid:c18efa1f-2981-4e3e-b11f-eccb6060db33

**Comment by krizovj** [comment]
Super, moc děkuju

**Comment by krizovj** [comment]
Teď koukám, že se u názvu rubriky "reklama" v angličtině objevuje v prohlížečce místo "Advertisement" jen "X"
![reklama](https://user-images.githubusercontent.com/21309201/43190386-379334f6-8ff9-11e8-8e37-f2e520e41b0e.jpg)

**Comment by albertoh** [comment]
Opraveno

**Comment by krizovj** [comment]
Pořád mi nefunguje to vyhledávání v těch rubrikách. 
Je to popsáno úplně na začátku tohoto issue.

**Comment by albertoh** [comment]
Opraveno

**Comment by krizovj** [comment]
u těch rubrik mi to vyhledává podle toho jejich označení v MODS záznamu. Potřebuju, aby to vyhledávalo prostě v české verzi česky a v anglické anglicky. Když třeba napíšu v české verzi webu zprávy, z našeptávače nic nevyleze a musím napsat "news".

**Comment by albertoh** [comment]
Aha, ted rozumim...
Opraveno

**Comment by krizovj** [comment]
Šlo by u těch rubrik, aby se to po přepnutí do anglické verze z těch anglických variant názvů rubrik? 
Tedy, když budu mít aktivní českou verzi webu, tak se bude vyhledávat podle českých slov (zprávy, nekrology,...) a když se přepnu do anglické verze, tak aby se to vyhledáváno podle těch anglických ekvivalentů (news, obituaries,...)? Teď mi to funguje v obou jazykových verzích jen pro češtinu. 
Takže když jsem v anglické verzi, tak musí napsat "zprávy", aby mi to rubriku našlo.
