### ISSUE TITLE
Zobrazení v prohlížeči

### ISSUE THREAD

**Issue by krizovj** [incad/K5Journals#71]
Internet Explorer

- V IE (mám verzi 11) se mi na ostré verzi webu nezobrazuje obrázek obálky (www.knihyadejiny.cz), ale v Mozille, Chrome i v Opeře ano. Nevíte, čím by to mohlo být a případně co s tím? Na testovacím se to v IE zobrazuje.
![obalka](https://user-images.githubusercontent.com/21309201/43256233-6af40e5a-90cc-11e8-8925-caacc89d7f70.jpg)

Další problém mám s tiskem. U všeho se tam zobrazuje adresa (obrázek obálky, tlačítko k přihlášení apod..). 
![adresa](https://user-images.githubusercontent.com/21309201/43256383-d4323dba-90cc-11e8-8223-63681b67576a.jpg)
S tiskem souvisí další věc a sice, že pokud obsah stránky nestačí na jednu stranu, ale je delší, tak by se ten zbytek měl vytisknout na druhou stranu. V Mozille se ale ten text, který už se nevejde prostě usekne a druhou stranu to sice vytiskne, ale je prázdná. Nevíte, čím by to mohlo být? 

A jinak bychom se tedy domluvili a šlo by pak celou tu aplikaci přejmenovat? Aby to nebylo K5Journals, ale něco rozumnějšího, ještě dám vědět.

**Comment by albertoh** [comment]
Obalka bude fungovat v novem :)

Tisk je problem bootstrapu, css framework, ktere tady pouzivame. Vsechny weby, ktere ho pouzivaji zobrazuju url odkazu v te podobe. Slo by to odstranit, zalozte prosim issue.

Dalsi problemu tisku nemaji vubec jednoduche reseni. To se musi predpripravit to co chceme tisknout. A testovat v ruznych browserech a tiskarnach...

Az budete vedet jak pojmenovat aplikaci, napiste, zmenim.

**Comment by krizovj** [comment]
Aplikace by se měla jmenovat ASJournals.

Ohledně toho tisku, pana Dudu napadlo, jestli by to nešlo udělat tak, že by se tam dal přidat "PDF box" (doufám, že je to správně). Prostě kdy bych chtěla stránku vytisknout, tak někde kliknu třeba na nějaké tlačítko "tisk" a ono se vygeneruje PDF té stránky, to by pak tyhle problémy dělat nemělo, ne?

**Comment by pavelkocourek** [comment]
KNAV 11.7.
