### ISSUE TITLE
Navigace - divný znaky

### ISSUE THREAD

**Issue by krizovj** [incad/K5Journals#78]
V navigaci se objevují divné znaky:
http://147.231.63.181/k5journals/kad/pro-autory/recenzenti?lang=cs 

u jiného testovacího časopisu jsou "jen" otazníky:
http://147.231.63.181/k5journals/NovyOrient/o-casopisu/open-access

Vyzkoušeno v Chromu, Mozille a Opeře a všude to je.

**Comment by krizovj** [comment]
odstranit parametr jazyka z překladu

**Comment by krizovj** [comment]
Pořád to tam vidím
![otaznik](https://user-images.githubusercontent.com/21309201/58936176-75dc4400-876f-11e9-91e6-ab8ea7e3712c.jpg)

**Comment by albertoh** [comment]
Opraveno. 
Zbyly tam stare css
