### ISSUE TITLE
Citace

### ISSUE THREAD

**Issue by krizovj** [incad/K5Journals#79]
Citace už v Krameriovi fungují. 

Potřebujeme to propojit s tlačítkem na webu. 

Je to v novém klientovi. Stačí, aby se po kliknutí na tlačítko objevilo to stejné okno, jako v Krameriovi, ale jen pro článek. V Krameriovi je možné vytvořit citaci pro všechny úrovně časopisu (číslo, ročník, celé periodikum), to není na webu nutné. 
https://kramerius.lib.cas.cz/uuid/uuid:aae6d2b4-1882-4ade-9806-26e863db4214

Je to v horní části pravého sloupce.

**Comment by krizovj** [comment]
Prošla jsem všechny testovací časopisy. Posílám přehled, jak u nich vypadají citace. Vždy je nejdříve uvedena citace z webu a pak citace stejného článku z Krameria.

Je tam docela hodně chyb. Samozřejmě nerozumím tomu, jak se přesně citace generují na webech, ale většina těch připomínek by se podle mě vyřešila tím, že by se prostě stáhla na web citace, kterou vygeneruje Kramerius, protože ten je cituje v rámci možností hodně dobře.

Obecně:

- Chybí číslo ročníku (přestože je na webu uvedeno)
- Název a podnázev článku je oddělený tečkou, má tam být dvojtečka
- Název článku a název časopisu nejsou odděleny vůbec nijak, není mezi nimi ani mezera. Má tam být tečka a mezera.
- „Dostupné z“ je „odskočeno“ na další řádek, mělo by to pokračovat normálně za textem
- Zničehonic přestane tlačítko pro citace fungovat, i v rámci jednoho čísla. Vyrobím si citaci článku, přesunu se na další článek, ale pro ten už to nefunguje - akt: během testování jsem přišla na to, že alespoň u některých časopisů je možné citovat jen recenze, ale pro jiné články tlačítko nefunguje (Kontradikce, Vesmír)
- Vydavatel se bere z úvodního webu (asi), proč se nebere ze záznamu v Krameriovi? 
- Chybí místo vydání
- Doplnit informaci o tom, že jde o citaci podle normy ISO 690 (viz. Kramerius)
- Datum vydání by se mělo brát taky z dat v Krameriovi, ale nebere
- Další poznámky uvádím níže u konkrétních časopisů

**Acta geodynamica et geomaterialia** (http://147.231.63.181/k5journals/AGG/archiv)
- bez obsahu, netestováno

------------------------------------------------------------------------------------------------------------------

**Collection of Czechoslovak chemical communications** (http://147.231.63.181/k5journals/Coll.%20of%20Czeslo%20chem.%20com./home)
- Text přelézá ven z okna (screenshot)
![odkazlezeven](https://user-images.githubusercontent.com/21309201/60002173-724e2580-9668-11e9-9734-2dacd65ae8a6.jpg)
- Špatné jméno autora – obojí je příjmení (ale ne u všech článků – někde je to správně) - viz. příklady níže
- Chybí ISSN
- V tomto časopisu jsou trochu jiná data – je totiž starší, ale v Krameriovi to je správně

_Příklady:_
**1) Web:**
SOBKOWSKI Sobkowski. A convenient protection for 4-oxopyrimidine moieties in nucleosides by the pivaloyl group_Collection of Czechoslovak Chemical Communications_. Archeologický ústav AV ČR, v. v. i., Praha. (1), 33 - 57. 
Dostupné také z: http://147.231.63.181/k5journals/Coll.%20of%20Czeslo%20chem.%20com./article/uuid:778151be-be79-11e2-9ddd-001e65b2b442

**1) Kramerius:** 
SOBKOWSKI, Michal. A convenient protection for 4-oxopyrimidine moieties in nucleosides by the pivaloyl group. _Collection of Czechoslovak chemical communications_. Praha: Ústav organické chemie a biochemie AV ČR, 2010, 75(1), 33-57. ISSN 0010-0765. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:778151be-be79-11e2-9ddd-001e65b2b442

**2) Web:**
BAREŠ Josef. RŮŽIČKA Aleš. ŠOUREK Vítězslav. MEUNIER Philippe. CÍSAŘOVÁ Ivana. PADĚLKOVÁ Zdeňka. PIRIO Nadine. HOLEČEK Jaroslav. Structure, properties and comparison of C,N-chelated and amido-stabilized plumbylenes_Collection of Czechoslovak Chemical Communications_. Archeologický ústav AV ČR, v. v. i., Praha. (1), 121 - 131. 
Dostupné také z: http://147.231.63.181/k5journals/Coll.%20of%20Czeslo%20chem.%20com./article/uuid:de91985d-be79-11e2-9ddd-001e65b2b442

**2) Kramerius:** 
BAREŠ, Josef et al. Structure, properties and comparison of C,N-chelated and amido-stabilized plumbylenes. _Collection of Czechoslovak chemical communications_. Praha: Ústav organické chemie a biochemie AV ČR, 2010, 75(1), 121-131. ISSN 0010-0765. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:de91985d-be79-11e2-9ddd-001e65b2b442

------------------------------------------------------------------------------------------------------------------

**Collection of Czechoslovak chemical communications** (http://147.231.63.181/k5journals/colchem/home)

- Viz. předchozí časopis, je to to samý

------------------------------------------------------------------------------------------------------------------

**Folia Zoologica** (http://147.231.63.181/k5journals/FoliaZOO/home)

_Příklady:_
**1) Web:** 
LEŠO Peter. KROPIL Rudolf. comparison of three different approaches for the classification of bird foraging guilds: an effect of leaf phenophase_Folia Zoologica_. Institute of Vertebrate Biology, Academy of Sciences of the Czech Republic. (1), 51 - 70. 
Dostupné také z: http://147.231.63.181/k5journals/FoliaZOO/article/uuid:e2925256-e436-c7fa-827e-0fb8ce47ed4d

**1) Kramerius:**
LEŠO, Peter a KROPIL, Rudolf. A comparison of three different approaches for the classification of bird foraging guilds: an effect of leaf phenophase. _Folia zoologica: International Journal of Vertebrate Zoology_. Brno: Ústav ekologie krajiny AV ČR, 2007, 56(1), 51-70. ISSN 0139-7893. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:e2925256-e436-c7fa-827e-0fb8ce47ed4d


**2) Web:**
CHEN Youhua. Distribution patterns and faunal characteristic of mammals on Hainan Island of China_Folia Zoologica_. Institute of Vertebrate Biology, Academy of Sciences of the Czech Republic. (4), 372 - 384. 
Dostupné také z: http://147.231.63.181/k5journals/FoliaZOO/article/uuid:3f2c31a2-b464-8777-61cb-b78902ddf9f5

**2) Kramerius:**
CHEN, Youhua. Distribution patterns and faunal characteristic of mammals on Hainan Island of China. _Folia zoologica: International Journal of Vertebrate Zoology_. Brno: Ústav ekologie krajiny AV ČR, 2009, 58(4), 372-384. ISSN 0139-7893. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:3f2c31a2-b464-8777-61cb-b78902ddf9f5

---------------------------------------------------------------------------------------------------------------

**Knihy a dějiny** (http://147.231.63.181/k5journals/knihyadejiny/home)

_Příklady:_

**1) Web:**
Mach, David. Tisk Pavla Sessia z roku 1623 s kopiemi grafik od Albrechta Dürera._Knihy a dějiny_. Knihovna AV ČR, v. v. i.. 2017, (1-2), 6 - 28. ISSN 1210-8510. 
Dostupné také z: http://147.231.63.181/k5journals/knihyadejiny/article/uuid:47c7e0d4-1ea7-4a6c-b52c-9d358d336f11

**1) Kramerius:**
MACH, David. Tisk Pavla Sessia z roku 1623 s kopiemi grafik od Albrechta Dürera. _Knihy a dějiny_. Praha: Knihovna AV ČR, 2017, 24(1-2), 6-28. ISSN 1210-8510. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:47c7e0d4-1ea7-4a6c-b52c-9d358d336f11

**2) Web:** 
1970- undefined. 1972- undefined. Roger Chartier v Praze_Knihy a dějiny_. Knihovna AV ČR, v. v. i.. 2016, (1-2), 173 - 175. ISSN 1210-8510. 
Dostupné také z: http://147.231.63.181/k5journals/knihyadejiny/article/uuid:c9e1bc2b-2627-4405-8c0c-1610eaa4e4d9

**2) Kramerius:** 
MÁDLOVÁ, Claire a JELÍNKOVÁ, Andrea. Roger Chartier v Praze. _Knihy a dějiny_. Praha: Knihovna AV ČR, 2016, 23(1-2), 173-175. ISSN 1210-8510. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:c9e1bc2b-2627-4405-8c0c-1610eaa4e4d9

---------------------------------------------------------------------------------------------------------------

**Knihy a dějiny** (http://147.231.63.181/k5journals/kad/home)
- Stejná data jako předchozí časopis

---------------------------------------------------------------------------------------------------------------

**Kontradikce** (http://147.231.63.181/k5journals/kontradikce/home)

- Citace nefungují, nepovedlo se mi vygenerovat ani jednu. Zkoušela jsem v Mozille a Chromu. Jde o nově založený časopis (24.6.2019).
- Aktualizace: Lze citovat jen recenze, nic jiného :D
	
---------------------------------------------------------------------------------------------------------------

**Nový Orient** (http://147.231.63.181/k5journals/NovyOrient/home)

_Příklady:_

**1) Web:**
Petrů, Tomáš F.. Lehce záhadný Harry J. Benda. k 95. výročí narození legendy světové indonesistiky. _Nový Orient : časopis Společnosti pro kulturní styky s Orientem_. Orientální ústav AV ČR, v. v. i.. 2014, (4), 58 - 64. ISSN 0029-5302. 
Dostupné také z: http://147.231.63.181/k5journals/NovyOrient/article/uuid:4e07a569-5b98-40df-a67c-3324ca3e11af

**1) Kramerius:**
PETRŮ, Tomáš F.. Lehce záhadný Harry J. Benda: k 95. výročí narození legendy světové indonesistiky. _Nový Orient: odborný čtvrtletník Orientálního ústavu AV ČR_. Praha: Orientální ústav, 27.01.2015, 69(4), 58-64. ISSN 0029-5302. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:4e07a569-5b98-40df-a67c-3324ca3e11af

**2) Web:**
Kondrys, Jan. Alí Abd ar-Ráziq a otázka politického sekularismu v islámu. _Nový Orient : časopis Společnosti pro kulturní styky s Orientem_. Orientální ústav AV ČR, v. v. i.. 2014, (1), 42 - 47. ISSN 0029-5302. 
Dostupné také z: http://147.231.63.181/k5journals/NovyOrient/article/uuid:c2185f16-6ee7-4ab1-b135-829808f0a6ea

**2) Kramerius:**
KONDRYS, Jan. Alí Abd ar-Ráziq a otázka politického sekularismu v islámu. _Nový Orient: odborný čtvrtletník Orientálního ústavu AV ČR_. Praha: Orientální ústav, 01.04.2014, 69(1), 42-47. ISSN 0029-5302. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:c2185f16-6ee7-4ab1-b135-829808f0a6ea


**3) Web:**
Žďárský, Pavel. Alois Musil jako zakladatel československé orientalistiky - ve službách republiky. _Nový Orient._ Orientální ústav AV ČR, v. v. i.. 2014, (1), 54 - 60. 
Dostupné také z: http://147.231.63.181/k5journals/NovyOrient/article/uuid:356ddc18-b324-4c42-bcb6-0a25b99914a0

**3) Kramerius:**
ŽĎÁRSKÝ, Pavel. Alois Musil jako zakladatel československé orientalistiky - ve službách republiky. _Nový Orient: odborný čtvrtletník Orientálního ústavu AV ČR_. Praha: Orientální ústav, 01.04.2014, 69(1), 54-60. ISSN 0029-5302. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:356ddc18-b324-4c42-bcb6-0a25b99914a0

---------------------------------------------------------------------------------------------------------------

**Právník** (http://147.231.63.181/k5journals/Pravnik/home)

- Citace nefungují, nepovedlo se mi vygenerovat ani jednu. Zkoušela jsem v Mozille a Chromu. 
- Během testování jsem přišla na to, že je možné citovat jen recenze, nic jiného. A v případě recenzí je citace úplně blbě. Viz. příklad níže (název časopisu je zřejmě názvem recenzovaného dokumentu, asi...)

CVRČEK František. Colotka Peter – Káčer Marek – Berdisová Lucia. Právna filozofia dvadsiateho storočia_Právna filozofia dvadsiateho storočia_. Ústav státu a práva AV ČR. 2016, (11), 1014 - 1016. 
Dostupné také z: http://147.231.63.181/k5journals/Pravnik/article/uuid:7fe5468f-b41c-478f-8176-fe400e26c706

---------------------------------------------------------------------------------------------------------------

**Vesmír** (http://147.231.63.181/k5journals/vesmir1/home)

- Opět tlačítko funguje jen pro recenze...
- Chybí název časopisu...

**Web:**
ŠOLC Roman. Anti-popularizace teorie superstrunDokonce ani ne špatně : lesk a bída strunové teorie. Knihovna AV ČR, v. v. i.. 2013, (1), 54 - 54. 
Dostupné také z: http://147.231.63.181/k5journals/vesmir1/article/uuid:cdf85d3e-3ea2-40c5-8fca-bb4b79707183

**Kramerius:**
ŠOLC, Roman. Anti-popularizace teorie superstrun. _Vesmír: časopis pro šíření vědy přírodní, země- a národopisné_. Praha: Václav F. Kumpošt, 10.01.2013, 92 (143)(1), 54. ISSN 0042-4544. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:cdf85d3e-3ea2-40c5-8fca-bb4b79707183

---------------------------------------------------------------------------------------------------------------

**Vesmír** (http://147.231.63.181/k5journals/Vesmir/home)

- Lze citovat jen recenze, nic jiného :D
- v citaci chybí název časopisu

_Příklady:_

**1) Web:**
NAKONEČNÝ Milan. K pramenům iracionalitySkrytá autorita : iracionalita a dav v člověku. Knihovna AV ČR, v. v. i.. 2013, (1), 53 - 54. 
Dostupné také z: http://147.231.63.181/k5journals/Vesmir/article/uuid:13c260ad-cc84-487d-a6fc-a3358431550f

**1) Kramerius:**
NAKONEČNÝ, Milan. K pramenům iracionality. _Vesmír: časopis pro šíření vědy přírodní, země- a národopisné_. Praha: Václav F. Kumpošt, 10.01.2013, 92 (143)(1), 53-54. ISSN 0042-4544. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:13c260ad-cc84-487d-a6fc-a3358431550f

**2) Web:**
HAVEL Ivan M.. Kniha kouzelSlavná Hofstadterova kniha konečně v českém překladu. II. _Gödel, Escher, Bach : existenciální gordická balada_. Knihovna AV ČR, v. v. i.. 2013, (1), 51 - 53. 
Dostupné také z: http://147.231.63.181/k5journals/Vesmir/article/uuid:49a1f334-f11b-4394-ac66-9645e978d553

**2) Kramerius:**
HAVEL, Ivan M.. Kniha kouzel: Slavná Hofstadterova kniha konečně v českém překladu, II. _Vesmír: časopis pro šíření vědy přírodní, země- a národopisné_. Praha: Václav F. Kumpošt, 10.01.2013, 92 (143)(1), 51-53. ISSN 0042-4544. Dostupné také z: https://kramerius.lib.cas.cz/uuid/uuid:49a1f334-f11b-4394-ac66-9645e978d553

**Comment by pavelkocourek** [comment]
Doplnit citaci pro K5J #254
Přesunuto na web klient - KNAV 11.7.
