### ISSUE TITLE
Zařazení v databázích

### ISSUE THREAD

**Issue by krizovj** [incad/K5Journals#89]
Tohle asi můžete označit jako enhancement, ale je to dost důležité. Na všech webech je na hlavní stránce uvedeno v kterých jsou databázích. Jenže je to tam napevno a nejde to změnit a ani vymazat. 
![databazee](https://user-images.githubusercontent.com/21309201/60009071-7af92880-9675-11e9-8b5a-cde6f922e33c.jpg)

**Comment by pavelkocourek** [comment]
označeno

**Comment by pavelkocourek** [comment]
KNAV 11.7.
